#! /bin/sh

# Fix socket error
sudo socket -blfq -s /dev/log
sudo chmod 777 /dev/log

# Start the OpenSSH service
sudo service ssh start

# Start the SageMathCell
cd ~/sc_build/sagecell
../sage/sage web_server.py
